/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 19/08/2021 09:45:23
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            16000000
#define MX_SYSCLKFreq_VALUE                     120000000
#define MX_HCLKFreq_Value                       120000000
#define MX_FCLKCortexFreq_Value                 120000000
#define MX_CortexFreq_Value                     120000000
#define MX_AHBFreq_Value                        120000000
#define MX_APB1Freq_Value                       120000000
#define MX_APB2Freq_Value                       120000000
#define MX_APB1TimFreq_Value                    120000000
#define MX_APB2TimFreq_Value                    120000000
#define MX_LCDTFTFreq_Value                     21000000
#define MX_PWRFreq_Value                        120000000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        16000000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    120000000

/*-------------------------------- DMA2D      --------------------------------*/

#define MX_DMA2D                                1

/* GPIO Configuration */

/*-------------------------------- DSIHOST    --------------------------------*/

#define MX_DSIHOST                              1

/* GPIO Configuration */

/* Pin DSIHOST_D0N */
#define MX_DSIHOST_D0N_Pin                      DSIHOST_D0N

/* Pin DSIHOST_D1N */
#define MX_DSIHOST_D1N_Pin                      DSIHOST_D1N

/* Pin DSIHOST_D0P */
#define MX_DSIHOST_D0P_Pin                      DSIHOST_D0P

/* Pin DSIHOST_D1P */
#define MX_DSIHOST_D1P_Pin                      DSIHOST_D1P

/* Pin DSIHOST_CKN */
#define MX_DSIHOST_CKN_Pin                      DSIHOST_CKN

/* Pin DSIHOST_CKP */
#define MX_DSIHOST_CKP_Pin                      DSIHOST_CKP

/*-------------------------------- GFXMMU     --------------------------------*/

#define MX_GFXMMU                               1

/* GPIO Configuration */

/*-------------------------------- LTDC       --------------------------------*/

#define MX_LTDC                                 1

/* GPIO Configuration */

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */

